name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env: 
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run Streamlit app
        run: |
          cd src
          timeout 10s streamlit run ./streamlit_app.py --server.headless true || echo "Streamlit app exited with code $?"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            damiancapdevila/damian-capdevila-website:${{ github.sha }}
            damiancapdevila/damian-capdevila-website:latest
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            CV_PRESALES_URL=${{ secrets.CV_PRESALES_URL }}
            CV_SOFTWARE_URL=${{ secrets.CV_SOFTWARE_URL }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Staging)
        if: github.ref == 'refs/heads/dev'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'damian-capdevila-staging'
          images: 'damiancapdevila/damian-capdevila-website:latest'

      - name: Deploy to Azure Web App (Production)
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'damian-capdevila-production'
          images: 'damiancapdevila/damian-capdevila-website:latest'
