name: Streamlit CI/CD

on:
    push:
        branches:
            - dev
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              env: 
                PYTHONPATH: ${{ github.workspace }}/src
              run: |
                pytest --maxfail=1 --disable-warnings -q

            - name: Run Streamlit app
              run: |
                cd src
                timeout 10s streamlit run ./streamlit_app.py --server.headless true || echo "Streamlit app exited with code $?"
