name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up environment variables
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "CV_PRESALES_URL=${{ secrets.CV_PRESALES_URL }}" >> $GITHUB_ENV
        echo "CV_SOFTWARE_URL=${{ secrets.CV_SOFTWARE_URL }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          damiancapdevila/damian-capdevila-website:${{ github.sha }}
          damiancapdevila/damian-capdevila-website:latest

    - name: Set Web App Name
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "AZURE_WEBAPP_NAME=damian-capdevila-production" >> $GITHUB_ENV
        else
          echo "AZURE_WEBAPP_NAME=damian-capdevila-staging" >> $GITHUB_ENV
        fi

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: 'damiancapdevila/damian-capdevila-website:latest'
